version: "3.4"
services:
  my_frontend:
    container_name: frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true